name: Django CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Checks
      run: python manage.py check

    - name: Run Tests
      run: python manage.py test